language: "perl"
perl:
  - "5.26"
install:
        - "cpanm --verbose --installdeps --notest ."
script:
        - "perl -cT photodb"
        - "perl -w check-usage-docs.pl"
        - "perlcritic photodb"
