language: perl
perl:
- '5.26'
env:
  global:
  - PERL5LIB=$TRAVIS_BUILD_DIR/lib
  - secure: ERaAHRIEwrs9nuQGomdFizcsMwlh150KGD6nd45NZ+qvIKDFnOHuIOAwtsX4ptCfUIWjJl4qTIpAEno3x2sONZgrUMsudEIiVfngc2nycf5+mvZDbfcJUJXG4cXtSkQA63jtpuq9G/TOTtJ1vZdtL+9def6VsuV9Bbm3udPe8iI=
services:
  - mysql
before_install:
  - mysql -e "create schema photodb; GRANT ALL PRIVILEGES ON photodb.* TO photodb@localhost IDENTIFIED BY 'photodb'"
  - mkdir -p ~/.photodb
  - echo -e "[database]\nuser=photodb\nschema=photodb\npass=photodb\nhost=localhost" > ~/.photodb/photodb.ini
install: cpanm --quiet --installdeps --notest --skip-satisfied .
jobs:
  include:
  - stage: dump
    script: mysqldump && ./dump-schema.pl --hostname=localhost --database=photodb --username=photodb --password=photodb && git status
  - stage: test
    name: Perl tests
    script: perl Build.PL && ./Build test
  - stage: deploy
    if: tag IS present
    script: perl Build.PL && ./Build manifest && ./Build && ./Build dist
    deploy:
    - provider: releases
      api_key:
        secure: D16t4VJ9pHLDbdEu6XQ0kVAEWYbjgIRrz6y6S4n72nCU2LBkhdbATyjb/VAVFLesskQVr9aS90b7vJHR+2Jl+ID0D9CpG3pJnBIB+ZB/ECMDN3EVzuqZxHl/pX+FRNPrpH548TShnK0TiRPCOdIr6NCeugBBKchCtSRuXG4Omgs=
      file: App-PhotoDB-${TRAVIS_TAG}.tar.gz
      on:
        tags: true
      skip_cleanup: true
      overwrite: true
    - provider: script
      before_script: cpanm -q CPAN::Uploader
      script: cpan-upload -u JGAZELEY -p ${PAUSE_PASS} App-PhotoDB-${TRAVIS_TAG}.tar.gz
      on:
        tags: true
      skip_cleanup: true
